version: '3.4'

services:
  cs-react-antd:
    image: cs-react-antd
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      API: https://api.dev.icankids.com.vn
      
    ports:
      - 3001:3001
    command: ["yarn", "start"]